const Arrow = () => <span aria-hidden="true">↗</span>;

const process = [
  ["01", "Organiza", "Edital, prazos, documentos e fontes deixam de existir de forma dispersa."],
  ["02", "Contextualiza", "Histórico, fornecedores, preços e capacidade operacional ampliam a leitura."],
  ["03", "Compara", "Orçamentos, critérios e evidências tornam diferenças e restrições visíveis."],
  ["04", "Recomenda", "O Decision Engine consolida os sinais para apoiar a decisão da empresa."],
];

export default function Plataforma() {
  return <main className="platform-page" id="top">
    <header className="platform-nav"><nav className="container" aria-label="Navegação principal">
      <a className="platform-logo" href="/" aria-label="SintExec — página inicial"><img src="/logo-sintexec.png" alt="SintExec" /></a>
      <div><a className="active" href="/plataforma">Plataforma</a><a href="/tecnologia">Tecnologia</a><a href="/contato">Contato</a><a href="/#principios">Princípios</a></div>
      <a className="platform-nav-cta" href="https://wa.me/5584996631083">Solicitar demonstração <Arrow/></a>
    </nav></header>

    <section className="platform-hero"><div className="platform-grid"></div><div className="container platform-hero-layout">
      <div className="platform-hero-copy"><span className="platform-kicker">A PLATAFORMA</span><h1>Inteligência para acompanhar todo o ciclo da oportunidade pública.</h1><p>O SintExec organiza informações, conecta evidências e transforma dados dispersos em contexto operacional para apoiar decisões mais seguras.</p><div className="platform-actions"><a className="platform-button primary" href="#como-funciona">Entenda como funciona <Arrow/></a><a className="platform-button secondary" href="https://wa.me/5584996631083">Solicite uma demonstração</a></div></div>
      <div className="platform-overview" aria-label="Visão conceitual da Central de Inteligência"><header><span>✦ Central de Inteligência</span><small>Oportunidade 2026-0187 · Em análise</small></header><div className="overview-content"><div className="overview-main"><small>PRIORIDADE ATUAL</small><h2>Aquisição de medicamentos hospitalares</h2><div className="overview-index"><span><b>87</b><small>índice consolidado</small></span><div><p><i style={{width:"92%"}}></i><b>Aderência ao objeto</b><strong>92</strong></p><p><i style={{width:"64%"}}></i><b>Capacidade operacional</b><strong>84</strong></p><p><i className="violet" style={{width:"48%"}}></i><b>Risco de prazo</b><strong>Médio</strong></p></div></div></div><aside><small>RECOMENDAÇÃO</small><h3>Avançar com ressalva</h3><p>Validar capacidade logística antes de iniciar a preparação.</p><span>Avaliação humana necessária</span></aside></div><footer><span>Dados organizados</span><i>→</i><span>Contexto aplicado</span><i>→</i><span>Recomendação explicável</span></footer></div>
    </div></section>

    <section className="platform-explanation" id="como-funciona"><div className="container explanation-layout"><div className="platform-heading"><span className="platform-kicker dark">01 / COMO FUNCIONA</span><h2>Uma oportunidade deixa de ser apenas um edital.</h2><p className="lead">Toda oportunidade passa primeiro pela Central de Inteligência.</p><p>É nela que o SintExec reúne documentos, prazos, fontes, fornecedores, referências de preço e informações da própria empresa. Esses dados passam a compartilhar o mesmo contexto e deixam de exigir que a equipe reconstrua a análise em diferentes ferramentas.</p><p>A plataforma acompanha a evolução da oportunidade. Novas evidências atualizam os indicadores, restrições tornam-se visíveis e a equipe preserva o histórico que fundamentou cada decisão.</p><blockquote>A Central não substitui a experiência da equipe. Ela oferece uma base mais organizada para que essa experiência seja aplicada.</blockquote></div><div className="explanation-panel"><header><span>CONTEXTO DA OPORTUNIDADE</span><b>6 fontes conectadas</b></header>{[["Edital e anexos","Documentação estruturada","100%"],["Histórico do órgão","126 eventos relacionados","94%"],["Referências de mercado","8 fornecedores consultados","86%"],["Capacidade da empresa","Critérios operacionais","82%"]].map(([title,detail,value],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{detail}</p></div><strong>{value}</strong></article>)}<footer><i></i><span>Contexto atualizado conforme a oportunidade evolui</span></footer></div></div></section>

    <section className="platform-process"><div className="container"><div className="platform-heading light"><span className="platform-kicker">02 / FLUXO DE INTELIGÊNCIA</span><h2>Da informação à decisão.</h2><p>O produto não apresenta capacidades isoladas. Cada etapa desenvolve o contexto recebido da etapa anterior.</p></div><ol>{process.map(([n,title,text])=><li key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><p className="process-note"><span>Oportunidade</span><i>→</i><span>Central de Inteligência</span><i>→</i><span>Decision Engine</span><i>→</i><span>Decisão da empresa</span></p></div></section>

    <section className="platform-decision"><div className="container decision-layout"><div className="platform-heading"><span className="platform-kicker dark">03 / DECISION ENGINE</span><h2>O Decision Engine organiza a complexidade.</h2><p>Centenas de informações isoladas têm pouco valor. O Decision Engine consolida sinais, aplica critérios definidos pela empresa e apresenta uma recomendação fundamentada.</p><p>O resultado não é uma decisão automática. É uma leitura estruturada que mostra aderência, risco, confiança e o racional utilizado, permitindo que a equipe avalie o cenário com clareza.</p><strong>Ele não decide pela empresa. Ajuda a decidir com mais contexto e confiança.</strong></div><div className="decision-summary"><header><span>ANÁLISE CONSOLIDADA</span><small>Atualizada agora</small></header><div className="decision-score"><span><b>87</b><small>/100</small></span><div><small>RECOMENDAÇÃO</small><h3>Avançar</h3><p>Alta aderência com uma ressalva operacional.</p></div></div><dl><div><dt>Aderência</dt><dd>92 · Alta</dd></div><div><dt>Risco</dt><dd>Médio</dd></div><div><dt>Confiança</dt><dd>Alta</dd></div></dl><div className="decision-rationale"><small>PRINCIPAL RACIONAL</small><p>Objeto compatível com o histórico da empresa. O prazo logístico deve ser validado antes da preparação.</p></div><footer><i></i><span><b>Avaliação humana necessária</b><small>A recomendação precisa ser revisada pela equipe responsável.</small></span></footer></div></div></section>

    <section className="platform-outlook"><div className="container outlook-layout"><div><span className="platform-kicker dark">04 / EVOLUÇÃO E CONFIANÇA</span><h2>Uma plataforma preparada para evoluir com responsabilidade.</h2></div><div className="outlook-copy"><article><span>EM EVOLUÇÃO</span><h3>Sint AI</h3><p>Está sendo desenvolvido para permitir consultas mais naturais sobre editais, documentos e riscos. Ainda não é uma funcionalidade disponível e não possui data pública de lançamento.</p></article><article><span>DESDE A BASE</span><h3>Segurança e rastreabilidade</h3><p>Controle de acesso, permissões, histórico de alterações, isolamento de dados e justificativas preservadas fazem parte da visão institucional do produto.</p></article></div></div></section>

    <section className="platform-final"><div className="platform-grid"></div><div className="container"><span className="platform-kicker">CONHEÇA A PLATAFORMA</span><h2>Conheça o SintExec em funcionamento.</h2><p>A melhor forma de compreender a plataforma é vê-la apoiando decisões reais.</p><div><a className="platform-button primary" href="https://wa.me/5584996631083">Solicite uma demonstração <Arrow/></a><a className="platform-button secondary" href="mailto:contato@sintexec.com.br">Fale com nosso time</a></div></div></section>

    <footer className="platform-footer"><div className="container"><a href="/" aria-label="SintExec — página inicial"><img src="/logo-sintexec.png" alt="SintExec" /></a><span>Inteligência em Licitações</span><div><a href="/">Home</a><a href="/plataforma">Plataforma</a><a href="/tecnologia">Tecnologia</a><a href="/contato">Contato</a><a href="#top">Topo ↑</a></div></div></footer>
  </main>;
}
